version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - ${ETHERNAUTS_REDIS_FOLDER}:/data

  keeper-queue:
    build:
      context: https://github.com/ethernautdao/ethernauts.git#main
      dockerfile: docker/keeper.production.Dockerfile
    command: npm run -w @ethernauts/keeper queue -- --no-compile --network ${ETHERNAUTS_NETWORK}
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINTS_QUEUE_NAME: mints-${ETHERNAUTS_NETWORK}
      RESOURCES_METADATA_FOLDER: ${ETHERNAUTS_RESOURCES_METADATA_FOLDER}
      RESOURCES_ASSETS_FOLDER: ${ETHERNAUTS_RESOURCES_ASSETS_FOLDER}
      FLEEK_API_KEY: ${ETHERNAUTS_FLEEK_API_KEY}
      FLEEK_STORAGE_API_KEY: ${ETHERNAUTS_FLEEK_STORAGE_API_KEY}
      FLEEK_STORAGE_API_SECRET: ${ETHERNAUTS_FLEEK_STORAGE_API_SECRET}
    restart: always
    depends_on:
      - redis

  keeper-worker:
    build:
      context: https://github.com/ethernautdao/ethernauts.git#main
      dockerfile: docker/keeper.production.Dockerfile
    command: npm run -w @ethernauts/keeper worker -- --no-compile --network ${ETHERNAUTS_NETWORK}
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINTS_QUEUE_NAME: mints-${ETHERNAUTS_NETWORK}
      RESOURCES_METADATA_FOLDER: ${ETHERNAUTS_RESOURCES_METADATA_FOLDER}
      RESOURCES_ASSETS_FOLDER: ${ETHERNAUTS_RESOURCES_ASSETS_FOLDER}
      FLEEK_API_KEY: ${ETHERNAUTS_FLEEK_API_KEY}
      FLEEK_STORAGE_API_KEY: ${ETHERNAUTS_FLEEK_STORAGE_API_KEY}
      FLEEK_STORAGE_API_SECRET: ${ETHERNAUTS_FLEEK_STORAGE_API_SECRET}
    restart: always
    depends_on:
      - redis
